import { signIn, signOut, useSession } from "next-auth/react";
import Head from "next/head";
import Image from "next/image";
import Link from "next/link";
import MediaCard from "~/components/MediaCard";
import Recommended from "~/components/MediaCard";
import Search from "~/components/Search";
import Title from "~/components/Title";

export default function Home() {
  return (
    <>
      <Head>
        <title>Entertainment</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon-32x32.png" />
      </Head>
      <div>
        <Search />
        <Title text="Trending" />
        <div className="pb-6">
          <div className="relative">
            <div className="absolute bottom-0 h-[70px] w-[240px] rounded-b-lg  bg-gradient-to-t from-[#000000] to-[#000000]/0"></div>
            <div className="absolute h-[140px] w-[240px]">
              <div className="absolute right-2 top-2 flex h-8 w-8 items-center justify-center rounded-full bg-[#000000]/50">
                <Image
                  src={"/images/icon-bookmark-v2.svg"}
                  alt="empty bookmark icon"
                  width={12}
                  height={14}
                />
              </div>
            </div>
            <div className="absolute bottom-4 left-4 flex flex-col text-[0.75rem] font-light text-white/75">
              <div className="flex items-center gap-2">
                <p>2019</p>
                <div className="h-[3px] w-[3px] rounded-full bg-[#979797]"></div>
                <p>Movie</p>
                <div className="h-[3px] w-[3px] rounded-full bg-[#979797]"></div>
                <p>PG</p>
              </div>
              <p className="text-body-m font-medium text-white">Beyond Earth</p>
            </div>
            <Image
              src={"/images/thumbnails/beyond-earth/trending/small.jpg"}
              alt="beyond earth thumbnail"
              width={240}
              height={140}
              className="rounded-lg"
            />
          </div>
        </div>
        <Title text="Recommended for you" />

        <div className="grid grid-cols-2 gap-4 pb-6">
          <MediaCard />
          <MediaCard />
          <MediaCard />
        </div>
      </div>
    </>
  );
}
