import { signIn, signOut, useSession } from "next-auth/react";
import Head from "next/head";
import Image from "next/image";
import Link from "next/link";
import Recommended from "~/components/Recommended";

export default function Home() {
  return (
    <>
      <Head>
        <title>Entertainment</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon-32x32.png" />
      </Head>
      <main className="h-screen bg-darkest-blue p-4 text-white">
        <div className="flex h-6 items-center gap-4 pb-6 pt-[80px]">
          <svg xmlns="http://www.w3.org/2000/svg" className="h-[32px] w-[32px]">
            <path
              d="M27.613 25.72 23.08 21.2a10.56 10.56 0 0 0 2.253-6.533C25.333 8.776 20.558 4 14.667 4S4 8.776 4 14.667c0 5.89 4.776 10.666 10.667 10.666A10.56 10.56 0 0 0 21.2 23.08l4.52 4.533a1.333 1.333 0 0 0 1.893 0 1.333 1.333 0 0 0 0-1.893ZM6.667 14.667a8 8 0 1 1 16 0 8 8 0 0 1-16 0Z"
              fill="#FFF"
            />
          </svg>
          <input
            className="bg-darkest-blue text-[1rem] font-light text-white outline-none placeholder:font-light placeholder:text-white/50 sm:text-heading-m"
            type="text"
            placeholder="Search for movies or TV series"
          />
        </div>

        <p className="pb-4 text-[1.25rem] font-light sm:text-heading-l">
          Trending
        </p>
        <div className="pb-6">
          <div className="relative">
            <div className="absolute bottom-0 h-[70px] w-[240px] rounded-b-lg  bg-gradient-to-t from-[#000000] to-[#000000]/0"></div>
            <div className="absolute h-[140px] w-[240px]">
              <div className="absolute right-2 top-2 flex h-8 w-8 items-center justify-center rounded-full bg-[#000000]/50">
                <Image
                  src={"/images/icon-bookmark-v2.svg"}
                  alt="empty bookmark icon"
                  width={12}
                  height={14}
                />
              </div>
            </div>
            <div className="absolute bottom-4 left-4 flex flex-col text-[0.75rem] font-light text-white/75">
              <div className="flex items-center gap-2">
                <p>2019</p>
                <div className="h-[3px] w-[3px] rounded-full bg-[#979797]"></div>
                <p>Movie</p>
                <div className="h-[3px] w-[3px] rounded-full bg-[#979797]"></div>
                <p>PG</p>
              </div>
              <p className="text-body-m font-medium text-white">Beyond Earth</p>
            </div>
            <Image
              src={"/images/thumbnails/beyond-earth/trending/small.jpg"}
              alt="beyond earth thumbnail"
              width={240}
              height={140}
              className="rounded-lg"
            />
          </div>
        </div>
        <p className="pb-4 text-[1.25rem] font-light sm:text-heading-l">
          Recommended for you
        </p>

        <div className="grid grid-cols-2 gap-4 pb-6">
          <Recommended />
          <Recommended />
          <Recommended />
        </div>
      </main>
    </>
  );
}
